---
- name: elasticsearch_conf | configuring elasticsearch
  template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch
  when: (es_docker_install is defined and not es_docker_install) or es_docker_install is not defined

- name: elasticsearch_conf | configuring elasticsearch
  template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: /usr/share/elasticsearch/config/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0750
  notify: restart elasticsearch
  when: (es_docker_install is defined and es_docker_install)

- name: elasticsearch_conf | configuring elasticsearch service
  template:
    src: etc/default/elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch
