---
# head plugin
#- include: plugins/head.yml
#  when: install_head is defined and install_head

# marvel plugin
#- include: plugins/marvel.yml
#  when: install_marvel is defined and install_marvel

# elasticHQ plugin
#- include: plugins/elastichq.yml
#  when: install_eshq is defined and install_eshq

# bigdesk plugin
#- include: plugins/bigdesk.yml
#  when: install_bigdesk is defined and install_bigdesk

# curator tool
- include: plugins/debian_curator.yml
  when: install_curator is defined and install_curator and ansible_os_family == "Debian"

- include: plugins/centos_curator.yml
  when: install_curator is defined and install_curator and ansible_os_family == "RedHat"

###Below is new method of installing plugins
- name: checking for existing plugins
  shell: '{{ es_plugin_bin }} {{ es_plugin_list }}'
  register: es_plugins_installed
  always_run: yes

- name: uninstalling plugins
  shell: '{{ es_plugin_bin }} -r {{ item }}'
  with_items: es_plugins_installed.stdout
  when: >
        (es_uninstall_plugins is defined and es_uninstall_plugins) and
        es_version|int == 1.7

- name: installing plugins
  command: '{{ es_plugin_bin }} {{ es_plugin_install }} {{ item.plugin }}{{ item.name }}'
  with_items: es_plugins_install
  when: item.name not in es_plugins_installed.stdout
